[package]
name = "bevy-canvas-2d"
version = "0.1.0"
edition = "2024"
authors = ["Freddy Wordingham <freddy@digilab.ai>"]

[dependencies]
bevy = "0.17"

[dev-dependencies]
rand = "0.9"
rand_chacha = "0.9"
